/**
 * Created by Ar-Krav on 29.01.2018.
 */

public with sharing class ConstantsUtil {
    public static final String allCityMode = 'all-cities';
    public static final Integer itemsOnOnePaginationPage = 20;

    public static final String TAB_TAG_PREFIX = 'sfdc.tabName';
    public static final String DEVICES_TAB_TAG = '01r1N000001NKig';
    public static final String HOME_TAB_TAG = '01r1N000001NKj0';
    public static final String SERVER_TAB_TAG = '01r1N000001NHuo';
}