table.list {
    border-width: 0 !important;
}
tr.dataRow.last td {
    border-bottom-width: 0 !important;
}
body .bPageBlock .pbBody .pbSubheader{
    background-color:#c0c0c0;
}
body .bPageBlock .pbBody .pbSubheader h3{
    color:#000;
}
.bPageBlock .detailList .dataCol{
    width: 100%;
 }
body .bPageBlock .pbBody .labelCol{
    text-align:left;
}
tr, td {
       max-width: 90px;
       word-break: break-word;
}