
#controlPanel {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    margin-bottom: 2%;
}

/*select*/

#cityDropDown {
    width: 10%;
    position: absolute;
}

.fulltable{
    display: none;
}

#alertImage{
    display: none;
}
tr td{
    max-width: 90px;
    word-break: break-word;
}

/*table*/

/*
 * Table styles

 */
#renderTable tfoot{
    display: table-header-group;
}
tfoot input {
    width: 100%;
    padding: 3px;
    box-sizing: border-box;
}
